version: "3"

services:
    frontend:
        build: ./frontend
        restart: always
        ports:
            - "9001:9001"
        volumes:
            - ./frontend:/frontend
            - /frontend/node_modules
        networks:
            - appnetwork

    backend:
        build: ./backend
        restart: always
        ports:
            - "4000:4000"
        volumes:
            - ./backend:/backend
            - /backend/node_modules
        networks:
            - appnetwork

networks:
    appnetwork:
        driver: bridge
